version: '3.8'

services:
  # Production build
  hash-core-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
    profiles:
      - production

  # Development build
  hash-core-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:8080"
    volumes:
      # Mount source code for hot reloading (optional)
      - ./packages/core/src:/app/packages/core/src
      - ./packages/engine-web/src:/app/packages/engine-web/src
    environment:
      - NODE_ENV=development
    profiles:
      - development

networks:
  default:
    name: hash-core-network 